package com.insuracne.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BeneficiaryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public BeneficiaryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBeneNameIsNull() {
            addCriterion("bene_name is null");
            return (Criteria) this;
        }

        public Criteria andBeneNameIsNotNull() {
            addCriterion("bene_name is not null");
            return (Criteria) this;
        }

        public Criteria andBeneNameEqualTo(String value) {
            addCriterion("bene_name =", value, "beneName");
            return (Criteria) this;
        }

        public Criteria andBeneNameNotEqualTo(String value) {
            addCriterion("bene_name <>", value, "beneName");
            return (Criteria) this;
        }

        public Criteria andBeneNameGreaterThan(String value) {
            addCriterion("bene_name >", value, "beneName");
            return (Criteria) this;
        }

        public Criteria andBeneNameGreaterThanOrEqualTo(String value) {
            addCriterion("bene_name >=", value, "beneName");
            return (Criteria) this;
        }

        public Criteria andBeneNameLessThan(String value) {
            addCriterion("bene_name <", value, "beneName");
            return (Criteria) this;
        }

        public Criteria andBeneNameLessThanOrEqualTo(String value) {
            addCriterion("bene_name <=", value, "beneName");
            return (Criteria) this;
        }

        public Criteria andBeneNameLike(String value) {
            addCriterion("bene_name like", value, "beneName");
            return (Criteria) this;
        }

        public Criteria andBeneNameNotLike(String value) {
            addCriterion("bene_name not like", value, "beneName");
            return (Criteria) this;
        }

        public Criteria andBeneNameIn(List<String> values) {
            addCriterion("bene_name in", values, "beneName");
            return (Criteria) this;
        }

        public Criteria andBeneNameNotIn(List<String> values) {
            addCriterion("bene_name not in", values, "beneName");
            return (Criteria) this;
        }

        public Criteria andBeneNameBetween(String value1, String value2) {
            addCriterion("bene_name between", value1, value2, "beneName");
            return (Criteria) this;
        }

        public Criteria andBeneNameNotBetween(String value1, String value2) {
            addCriterion("bene_name not between", value1, value2, "beneName");
            return (Criteria) this;
        }

        public Criteria andBeneContactIsNull() {
            addCriterion("bene_contact is null");
            return (Criteria) this;
        }

        public Criteria andBeneContactIsNotNull() {
            addCriterion("bene_contact is not null");
            return (Criteria) this;
        }

        public Criteria andBeneContactEqualTo(String value) {
            addCriterion("bene_contact =", value, "beneContact");
            return (Criteria) this;
        }

        public Criteria andBeneContactNotEqualTo(String value) {
            addCriterion("bene_contact <>", value, "beneContact");
            return (Criteria) this;
        }

        public Criteria andBeneContactGreaterThan(String value) {
            addCriterion("bene_contact >", value, "beneContact");
            return (Criteria) this;
        }

        public Criteria andBeneContactGreaterThanOrEqualTo(String value) {
            addCriterion("bene_contact >=", value, "beneContact");
            return (Criteria) this;
        }

        public Criteria andBeneContactLessThan(String value) {
            addCriterion("bene_contact <", value, "beneContact");
            return (Criteria) this;
        }

        public Criteria andBeneContactLessThanOrEqualTo(String value) {
            addCriterion("bene_contact <=", value, "beneContact");
            return (Criteria) this;
        }

        public Criteria andBeneContactLike(String value) {
            addCriterion("bene_contact like", value, "beneContact");
            return (Criteria) this;
        }

        public Criteria andBeneContactNotLike(String value) {
            addCriterion("bene_contact not like", value, "beneContact");
            return (Criteria) this;
        }

        public Criteria andBeneContactIn(List<String> values) {
            addCriterion("bene_contact in", values, "beneContact");
            return (Criteria) this;
        }

        public Criteria andBeneContactNotIn(List<String> values) {
            addCriterion("bene_contact not in", values, "beneContact");
            return (Criteria) this;
        }

        public Criteria andBeneContactBetween(String value1, String value2) {
            addCriterion("bene_contact between", value1, value2, "beneContact");
            return (Criteria) this;
        }

        public Criteria andBeneContactNotBetween(String value1, String value2) {
            addCriterion("bene_contact not between", value1, value2, "beneContact");
            return (Criteria) this;
        }

        public Criteria andBeneAddressIsNull() {
            addCriterion("bene_address is null");
            return (Criteria) this;
        }

        public Criteria andBeneAddressIsNotNull() {
            addCriterion("bene_address is not null");
            return (Criteria) this;
        }

        public Criteria andBeneAddressEqualTo(String value) {
            addCriterion("bene_address =", value, "beneAddress");
            return (Criteria) this;
        }

        public Criteria andBeneAddressNotEqualTo(String value) {
            addCriterion("bene_address <>", value, "beneAddress");
            return (Criteria) this;
        }

        public Criteria andBeneAddressGreaterThan(String value) {
            addCriterion("bene_address >", value, "beneAddress");
            return (Criteria) this;
        }

        public Criteria andBeneAddressGreaterThanOrEqualTo(String value) {
            addCriterion("bene_address >=", value, "beneAddress");
            return (Criteria) this;
        }

        public Criteria andBeneAddressLessThan(String value) {
            addCriterion("bene_address <", value, "beneAddress");
            return (Criteria) this;
        }

        public Criteria andBeneAddressLessThanOrEqualTo(String value) {
            addCriterion("bene_address <=", value, "beneAddress");
            return (Criteria) this;
        }

        public Criteria andBeneAddressLike(String value) {
            addCriterion("bene_address like", value, "beneAddress");
            return (Criteria) this;
        }

        public Criteria andBeneAddressNotLike(String value) {
            addCriterion("bene_address not like", value, "beneAddress");
            return (Criteria) this;
        }

        public Criteria andBeneAddressIn(List<String> values) {
            addCriterion("bene_address in", values, "beneAddress");
            return (Criteria) this;
        }

        public Criteria andBeneAddressNotIn(List<String> values) {
            addCriterion("bene_address not in", values, "beneAddress");
            return (Criteria) this;
        }

        public Criteria andBeneAddressBetween(String value1, String value2) {
            addCriterion("bene_address between", value1, value2, "beneAddress");
            return (Criteria) this;
        }

        public Criteria andBeneAddressNotBetween(String value1, String value2) {
            addCriterion("bene_address not between", value1, value2, "beneAddress");
            return (Criteria) this;
        }

        public Criteria andSecondBeneNameIsNull() {
            addCriterion("second_bene_name is null");
            return (Criteria) this;
        }

        public Criteria andSecondBeneNameIsNotNull() {
            addCriterion("second_bene_name is not null");
            return (Criteria) this;
        }

        public Criteria andSecondBeneNameEqualTo(String value) {
            addCriterion("second_bene_name =", value, "secondBeneName");
            return (Criteria) this;
        }

        public Criteria andSecondBeneNameNotEqualTo(String value) {
            addCriterion("second_bene_name <>", value, "secondBeneName");
            return (Criteria) this;
        }

        public Criteria andSecondBeneNameGreaterThan(String value) {
            addCriterion("second_bene_name >", value, "secondBeneName");
            return (Criteria) this;
        }

        public Criteria andSecondBeneNameGreaterThanOrEqualTo(String value) {
            addCriterion("second_bene_name >=", value, "secondBeneName");
            return (Criteria) this;
        }

        public Criteria andSecondBeneNameLessThan(String value) {
            addCriterion("second_bene_name <", value, "secondBeneName");
            return (Criteria) this;
        }

        public Criteria andSecondBeneNameLessThanOrEqualTo(String value) {
            addCriterion("second_bene_name <=", value, "secondBeneName");
            return (Criteria) this;
        }

        public Criteria andSecondBeneNameLike(String value) {
            addCriterion("second_bene_name like", value, "secondBeneName");
            return (Criteria) this;
        }

        public Criteria andSecondBeneNameNotLike(String value) {
            addCriterion("second_bene_name not like", value, "secondBeneName");
            return (Criteria) this;
        }

        public Criteria andSecondBeneNameIn(List<String> values) {
            addCriterion("second_bene_name in", values, "secondBeneName");
            return (Criteria) this;
        }

        public Criteria andSecondBeneNameNotIn(List<String> values) {
            addCriterion("second_bene_name not in", values, "secondBeneName");
            return (Criteria) this;
        }

        public Criteria andSecondBeneNameBetween(String value1, String value2) {
            addCriterion("second_bene_name between", value1, value2, "secondBeneName");
            return (Criteria) this;
        }

        public Criteria andSecondBeneNameNotBetween(String value1, String value2) {
            addCriterion("second_bene_name not between", value1, value2, "secondBeneName");
            return (Criteria) this;
        }

        public Criteria andSecondBeneContactIsNull() {
            addCriterion("second_bene_contact is null");
            return (Criteria) this;
        }

        public Criteria andSecondBeneContactIsNotNull() {
            addCriterion("second_bene_contact is not null");
            return (Criteria) this;
        }

        public Criteria andSecondBeneContactEqualTo(String value) {
            addCriterion("second_bene_contact =", value, "secondBeneContact");
            return (Criteria) this;
        }

        public Criteria andSecondBeneContactNotEqualTo(String value) {
            addCriterion("second_bene_contact <>", value, "secondBeneContact");
            return (Criteria) this;
        }

        public Criteria andSecondBeneContactGreaterThan(String value) {
            addCriterion("second_bene_contact >", value, "secondBeneContact");
            return (Criteria) this;
        }

        public Criteria andSecondBeneContactGreaterThanOrEqualTo(String value) {
            addCriterion("second_bene_contact >=", value, "secondBeneContact");
            return (Criteria) this;
        }

        public Criteria andSecondBeneContactLessThan(String value) {
            addCriterion("second_bene_contact <", value, "secondBeneContact");
            return (Criteria) this;
        }

        public Criteria andSecondBeneContactLessThanOrEqualTo(String value) {
            addCriterion("second_bene_contact <=", value, "secondBeneContact");
            return (Criteria) this;
        }

        public Criteria andSecondBeneContactLike(String value) {
            addCriterion("second_bene_contact like", value, "secondBeneContact");
            return (Criteria) this;
        }

        public Criteria andSecondBeneContactNotLike(String value) {
            addCriterion("second_bene_contact not like", value, "secondBeneContact");
            return (Criteria) this;
        }

        public Criteria andSecondBeneContactIn(List<String> values) {
            addCriterion("second_bene_contact in", values, "secondBeneContact");
            return (Criteria) this;
        }

        public Criteria andSecondBeneContactNotIn(List<String> values) {
            addCriterion("second_bene_contact not in", values, "secondBeneContact");
            return (Criteria) this;
        }

        public Criteria andSecondBeneContactBetween(String value1, String value2) {
            addCriterion("second_bene_contact between", value1, value2, "secondBeneContact");
            return (Criteria) this;
        }

        public Criteria andSecondBeneContactNotBetween(String value1, String value2) {
            addCriterion("second_bene_contact not between", value1, value2, "secondBeneContact");
            return (Criteria) this;
        }

        public Criteria andSecondBeneAddressIsNull() {
            addCriterion("second_bene_address is null");
            return (Criteria) this;
        }

        public Criteria andSecondBeneAddressIsNotNull() {
            addCriterion("second_bene_address is not null");
            return (Criteria) this;
        }

        public Criteria andSecondBeneAddressEqualTo(String value) {
            addCriterion("second_bene_address =", value, "secondBeneAddress");
            return (Criteria) this;
        }

        public Criteria andSecondBeneAddressNotEqualTo(String value) {
            addCriterion("second_bene_address <>", value, "secondBeneAddress");
            return (Criteria) this;
        }

        public Criteria andSecondBeneAddressGreaterThan(String value) {
            addCriterion("second_bene_address >", value, "secondBeneAddress");
            return (Criteria) this;
        }

        public Criteria andSecondBeneAddressGreaterThanOrEqualTo(String value) {
            addCriterion("second_bene_address >=", value, "secondBeneAddress");
            return (Criteria) this;
        }

        public Criteria andSecondBeneAddressLessThan(String value) {
            addCriterion("second_bene_address <", value, "secondBeneAddress");
            return (Criteria) this;
        }

        public Criteria andSecondBeneAddressLessThanOrEqualTo(String value) {
            addCriterion("second_bene_address <=", value, "secondBeneAddress");
            return (Criteria) this;
        }

        public Criteria andSecondBeneAddressLike(String value) {
            addCriterion("second_bene_address like", value, "secondBeneAddress");
            return (Criteria) this;
        }

        public Criteria andSecondBeneAddressNotLike(String value) {
            addCriterion("second_bene_address not like", value, "secondBeneAddress");
            return (Criteria) this;
        }

        public Criteria andSecondBeneAddressIn(List<String> values) {
            addCriterion("second_bene_address in", values, "secondBeneAddress");
            return (Criteria) this;
        }

        public Criteria andSecondBeneAddressNotIn(List<String> values) {
            addCriterion("second_bene_address not in", values, "secondBeneAddress");
            return (Criteria) this;
        }

        public Criteria andSecondBeneAddressBetween(String value1, String value2) {
            addCriterion("second_bene_address between", value1, value2, "secondBeneAddress");
            return (Criteria) this;
        }

        public Criteria andSecondBeneAddressNotBetween(String value1, String value2) {
            addCriterion("second_bene_address not between", value1, value2, "secondBeneAddress");
            return (Criteria) this;
        }

        public Criteria andBeneRelationIsNull() {
            addCriterion("bene_relation is null");
            return (Criteria) this;
        }

        public Criteria andBeneRelationIsNotNull() {
            addCriterion("bene_relation is not null");
            return (Criteria) this;
        }

        public Criteria andBeneRelationEqualTo(String value) {
            addCriterion("bene_relation =", value, "beneRelation");
            return (Criteria) this;
        }

        public Criteria andBeneRelationNotEqualTo(String value) {
            addCriterion("bene_relation <>", value, "beneRelation");
            return (Criteria) this;
        }

        public Criteria andBeneRelationGreaterThan(String value) {
            addCriterion("bene_relation >", value, "beneRelation");
            return (Criteria) this;
        }

        public Criteria andBeneRelationGreaterThanOrEqualTo(String value) {
            addCriterion("bene_relation >=", value, "beneRelation");
            return (Criteria) this;
        }

        public Criteria andBeneRelationLessThan(String value) {
            addCriterion("bene_relation <", value, "beneRelation");
            return (Criteria) this;
        }

        public Criteria andBeneRelationLessThanOrEqualTo(String value) {
            addCriterion("bene_relation <=", value, "beneRelation");
            return (Criteria) this;
        }

        public Criteria andBeneRelationLike(String value) {
            addCriterion("bene_relation like", value, "beneRelation");
            return (Criteria) this;
        }

        public Criteria andBeneRelationNotLike(String value) {
            addCriterion("bene_relation not like", value, "beneRelation");
            return (Criteria) this;
        }

        public Criteria andBeneRelationIn(List<String> values) {
            addCriterion("bene_relation in", values, "beneRelation");
            return (Criteria) this;
        }

        public Criteria andBeneRelationNotIn(List<String> values) {
            addCriterion("bene_relation not in", values, "beneRelation");
            return (Criteria) this;
        }

        public Criteria andBeneRelationBetween(String value1, String value2) {
            addCriterion("bene_relation between", value1, value2, "beneRelation");
            return (Criteria) this;
        }

        public Criteria andBeneRelationNotBetween(String value1, String value2) {
            addCriterion("bene_relation not between", value1, value2, "beneRelation");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("comment is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("comment is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("comment =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("comment <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("comment >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("comment >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("comment <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("comment <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("comment like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("comment not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("comment in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("comment not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("comment between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("comment not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("create_by is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("create_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(Long value) {
            addCriterion("create_by =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(Long value) {
            addCriterion("create_by <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(Long value) {
            addCriterion("create_by >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(Long value) {
            addCriterion("create_by >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(Long value) {
            addCriterion("create_by <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(Long value) {
            addCriterion("create_by <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<Long> values) {
            addCriterion("create_by in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<Long> values) {
            addCriterion("create_by not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(Long value1, Long value2) {
            addCriterion("create_by between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(Long value1, Long value2) {
            addCriterion("create_by not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("update_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("update_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(Long value) {
            addCriterion("update_by =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(Long value) {
            addCriterion("update_by <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(Long value) {
            addCriterion("update_by >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(Long value) {
            addCriterion("update_by >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(Long value) {
            addCriterion("update_by <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(Long value) {
            addCriterion("update_by <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<Long> values) {
            addCriterion("update_by in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<Long> values) {
            addCriterion("update_by not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(Long value1, Long value2) {
            addCriterion("update_by between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(Long value1, Long value2) {
            addCriterion("update_by not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("delete_flag is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("delete_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(Byte value) {
            addCriterion("delete_flag =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(Byte value) {
            addCriterion("delete_flag <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(Byte value) {
            addCriterion("delete_flag >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(Byte value) {
            addCriterion("delete_flag >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(Byte value) {
            addCriterion("delete_flag <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(Byte value) {
            addCriterion("delete_flag <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<Byte> values) {
            addCriterion("delete_flag in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<Byte> values) {
            addCriterion("delete_flag not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(Byte value1, Byte value2) {
            addCriterion("delete_flag between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(Byte value1, Byte value2) {
            addCriterion("delete_flag not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_beneficiary
     *
     * @mbggenerated do_not_delete_during_merge Sat Mar 25 12:55:25 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}