package com.insuracne.entity;

import java.util.Date;

public class Beneficiary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_beneficiary.id
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_beneficiary.bene_name
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private String beneName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_beneficiary.bene_contact
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private String beneContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_beneficiary.bene_address
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private String beneAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_beneficiary.second_bene_name
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private String secondBeneName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_beneficiary.second_bene_contact
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private String secondBeneContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_beneficiary.second_bene_address
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private String secondBeneAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_beneficiary.bene_relation
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private String beneRelation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_beneficiary.comment
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_beneficiary.create_by
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_beneficiary.create_time
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_beneficiary.update_by
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_beneficiary.update_time
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_beneficiary.delete_flag
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private Byte deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_beneficiary.id
     *
     * @return the value of t_beneficiary.id
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_beneficiary.id
     *
     * @param id the value for t_beneficiary.id
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_beneficiary.bene_name
     *
     * @return the value of t_beneficiary.bene_name
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public String getBeneName() {
        return beneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_beneficiary.bene_name
     *
     * @param beneName the value for t_beneficiary.bene_name
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setBeneName(String beneName) {
        this.beneName = beneName == null ? null : beneName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_beneficiary.bene_contact
     *
     * @return the value of t_beneficiary.bene_contact
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public String getBeneContact() {
        return beneContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_beneficiary.bene_contact
     *
     * @param beneContact the value for t_beneficiary.bene_contact
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setBeneContact(String beneContact) {
        this.beneContact = beneContact == null ? null : beneContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_beneficiary.bene_address
     *
     * @return the value of t_beneficiary.bene_address
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public String getBeneAddress() {
        return beneAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_beneficiary.bene_address
     *
     * @param beneAddress the value for t_beneficiary.bene_address
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setBeneAddress(String beneAddress) {
        this.beneAddress = beneAddress == null ? null : beneAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_beneficiary.second_bene_name
     *
     * @return the value of t_beneficiary.second_bene_name
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public String getSecondBeneName() {
        return secondBeneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_beneficiary.second_bene_name
     *
     * @param secondBeneName the value for t_beneficiary.second_bene_name
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setSecondBeneName(String secondBeneName) {
        this.secondBeneName = secondBeneName == null ? null : secondBeneName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_beneficiary.second_bene_contact
     *
     * @return the value of t_beneficiary.second_bene_contact
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public String getSecondBeneContact() {
        return secondBeneContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_beneficiary.second_bene_contact
     *
     * @param secondBeneContact the value for t_beneficiary.second_bene_contact
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setSecondBeneContact(String secondBeneContact) {
        this.secondBeneContact = secondBeneContact == null ? null : secondBeneContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_beneficiary.second_bene_address
     *
     * @return the value of t_beneficiary.second_bene_address
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public String getSecondBeneAddress() {
        return secondBeneAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_beneficiary.second_bene_address
     *
     * @param secondBeneAddress the value for t_beneficiary.second_bene_address
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setSecondBeneAddress(String secondBeneAddress) {
        this.secondBeneAddress = secondBeneAddress == null ? null : secondBeneAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_beneficiary.bene_relation
     *
     * @return the value of t_beneficiary.bene_relation
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public String getBeneRelation() {
        return beneRelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_beneficiary.bene_relation
     *
     * @param beneRelation the value for t_beneficiary.bene_relation
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setBeneRelation(String beneRelation) {
        this.beneRelation = beneRelation == null ? null : beneRelation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_beneficiary.comment
     *
     * @return the value of t_beneficiary.comment
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_beneficiary.comment
     *
     * @param comment the value for t_beneficiary.comment
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_beneficiary.create_by
     *
     * @return the value of t_beneficiary.create_by
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_beneficiary.create_by
     *
     * @param createBy the value for t_beneficiary.create_by
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_beneficiary.create_time
     *
     * @return the value of t_beneficiary.create_time
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_beneficiary.create_time
     *
     * @param createTime the value for t_beneficiary.create_time
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_beneficiary.update_by
     *
     * @return the value of t_beneficiary.update_by
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_beneficiary.update_by
     *
     * @param updateBy the value for t_beneficiary.update_by
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_beneficiary.update_time
     *
     * @return the value of t_beneficiary.update_time
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_beneficiary.update_time
     *
     * @param updateTime the value for t_beneficiary.update_time
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_beneficiary.delete_flag
     *
     * @return the value of t_beneficiary.delete_flag
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public Byte getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_beneficiary.delete_flag
     *
     * @param deleteFlag the value for t_beneficiary.delete_flag
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setDeleteFlag(Byte deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}