package com.insuracne.entity;

import java.math.BigDecimal;
import java.util.Date;

public class InsuracneOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insuracne_order.id
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insuracne_order.ins_no
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private String insNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insuracne_order.bene_id
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private Long beneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insuracne_order.ins_type
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private Integer insType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insuracne_order.bene_amount
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private BigDecimal beneAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insuracne_order.bene_year
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private Integer beneYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insuracne_order.ins_start_date
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private Date insStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insuracne_order.ins_year
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private Integer insYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insuracne_order.comment
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insuracne_order.create_by
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insuracne_order.create_time
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insuracne_order.update_by
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insuracne_order.update_time
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insuracne_order.delete_flag
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    private Byte deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insuracne_order.id
     *
     * @return the value of t_insuracne_order.id
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insuracne_order.id
     *
     * @param id the value for t_insuracne_order.id
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insuracne_order.ins_no
     *
     * @return the value of t_insuracne_order.ins_no
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public String getInsNo() {
        return insNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insuracne_order.ins_no
     *
     * @param insNo the value for t_insuracne_order.ins_no
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setInsNo(String insNo) {
        this.insNo = insNo == null ? null : insNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insuracne_order.bene_id
     *
     * @return the value of t_insuracne_order.bene_id
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public Long getBeneId() {
        return beneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insuracne_order.bene_id
     *
     * @param beneId the value for t_insuracne_order.bene_id
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setBeneId(Long beneId) {
        this.beneId = beneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insuracne_order.ins_type
     *
     * @return the value of t_insuracne_order.ins_type
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public Integer getInsType() {
        return insType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insuracne_order.ins_type
     *
     * @param insType the value for t_insuracne_order.ins_type
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setInsType(Integer insType) {
        this.insType = insType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insuracne_order.bene_amount
     *
     * @return the value of t_insuracne_order.bene_amount
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public BigDecimal getBeneAmount() {
        return beneAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insuracne_order.bene_amount
     *
     * @param beneAmount the value for t_insuracne_order.bene_amount
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setBeneAmount(BigDecimal beneAmount) {
        this.beneAmount = beneAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insuracne_order.bene_year
     *
     * @return the value of t_insuracne_order.bene_year
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public Integer getBeneYear() {
        return beneYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insuracne_order.bene_year
     *
     * @param beneYear the value for t_insuracne_order.bene_year
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setBeneYear(Integer beneYear) {
        this.beneYear = beneYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insuracne_order.ins_start_date
     *
     * @return the value of t_insuracne_order.ins_start_date
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public Date getInsStartDate() {
        return insStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insuracne_order.ins_start_date
     *
     * @param insStartDate the value for t_insuracne_order.ins_start_date
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setInsStartDate(Date insStartDate) {
        this.insStartDate = insStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insuracne_order.ins_year
     *
     * @return the value of t_insuracne_order.ins_year
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public Integer getInsYear() {
        return insYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insuracne_order.ins_year
     *
     * @param insYear the value for t_insuracne_order.ins_year
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setInsYear(Integer insYear) {
        this.insYear = insYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insuracne_order.comment
     *
     * @return the value of t_insuracne_order.comment
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insuracne_order.comment
     *
     * @param comment the value for t_insuracne_order.comment
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insuracne_order.create_by
     *
     * @return the value of t_insuracne_order.create_by
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insuracne_order.create_by
     *
     * @param createBy the value for t_insuracne_order.create_by
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insuracne_order.create_time
     *
     * @return the value of t_insuracne_order.create_time
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insuracne_order.create_time
     *
     * @param createTime the value for t_insuracne_order.create_time
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insuracne_order.update_by
     *
     * @return the value of t_insuracne_order.update_by
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insuracne_order.update_by
     *
     * @param updateBy the value for t_insuracne_order.update_by
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insuracne_order.update_time
     *
     * @return the value of t_insuracne_order.update_time
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insuracne_order.update_time
     *
     * @param updateTime the value for t_insuracne_order.update_time
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insuracne_order.delete_flag
     *
     * @return the value of t_insuracne_order.delete_flag
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public Byte getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insuracne_order.delete_flag
     *
     * @param deleteFlag the value for t_insuracne_order.delete_flag
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    public void setDeleteFlag(Byte deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}