package com.insuracne.dao;

import com.insuracne.entity.Beneficiary;
import com.insuracne.entity.BeneficiaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BeneficiaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int countByExample(BeneficiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int deleteByExample(BeneficiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int insert(Beneficiary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int insertSelective(Beneficiary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    List<Beneficiary> selectByExample(BeneficiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    Beneficiary selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int updateByExampleSelective(@Param("record") Beneficiary record, @Param("example") BeneficiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int updateByExample(@Param("record") Beneficiary record, @Param("example") BeneficiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int updateByPrimaryKeySelective(Beneficiary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_beneficiary
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int updateByPrimaryKey(Beneficiary record);
}