package com.insuracne.dao;

import com.insuracne.entity.InsuracneType;
import com.insuracne.entity.InsuracneTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InsuracneTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insuracne_type
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int countByExample(InsuracneTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insuracne_type
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int deleteByExample(InsuracneTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insuracne_type
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insuracne_type
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int insert(InsuracneType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insuracne_type
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int insertSelective(InsuracneType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insuracne_type
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    List<InsuracneType> selectByExample(InsuracneTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insuracne_type
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    InsuracneType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insuracne_type
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int updateByExampleSelective(@Param("record") InsuracneType record, @Param("example") InsuracneTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insuracne_type
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int updateByExample(@Param("record") InsuracneType record, @Param("example") InsuracneTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insuracne_type
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int updateByPrimaryKeySelective(InsuracneType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insuracne_type
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int updateByPrimaryKey(InsuracneType record);
}