package com.insuracne.dao;

import com.insuracne.entity.InsuracneOrder;
import com.insuracne.entity.InsuracneOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InsuracneOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insuracne_order
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int countByExample(InsuracneOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insuracne_order
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int deleteByExample(InsuracneOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insuracne_order
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insuracne_order
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int insert(InsuracneOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insuracne_order
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int insertSelective(InsuracneOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insuracne_order
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    List<InsuracneOrder> selectByExample(InsuracneOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insuracne_order
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    InsuracneOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insuracne_order
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int updateByExampleSelective(@Param("record") InsuracneOrder record, @Param("example") InsuracneOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insuracne_order
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int updateByExample(@Param("record") InsuracneOrder record, @Param("example") InsuracneOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insuracne_order
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int updateByPrimaryKeySelective(InsuracneOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insuracne_order
     *
     * @mbggenerated Sat Mar 25 12:55:25 CST 2017
     */
    int updateByPrimaryKey(InsuracneOrder record);
}